version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: fundoo-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: fundoo-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
